
-- Inserir 10 novos perfis variados usando as imagens anexas
INSERT INTO public.profiles (
  name, matricula, email, cargo, funcao, unidade, telefone, biografia,
  areas_conhecimento, especializacoes, temas_interesse, idiomas,
  foto_url, certificacoes, publicacoes, aceite_termos, is_active, role
) VALUES
(
  'Maria Silva Santos',
  'MAT001',
  'maria.santos@mprj.mp.br',
  ARRAY['Promotora de Justiça'],
  ARRAY['Coordenadora'],
  ARRAY['Promotoria de Justiça'],
  '(21) 2334-5678',
  'Promotora de Justiça especializada em direitos humanos e proteção à mulher, com mais de 10 anos de experiência no MPRJ.',
  ARRAY['Direitos Humanos', 'Violência Doméstica', 'Direito Penal'],
  'Especialização em Direito Penal e Processo Penal',
  ARRAY['Proteção à Mulher', 'Lei Maria da Penha', 'Crimes contra Dignidade Sexual'],
  ARRAY['Português', 'Inglês', 'Espanhol'],
  '/lovable-uploads/651c4793-fc08-41e1-81f6-6140802a9fa6.png',
  ARRAY['Certificação em Direitos Humanos', 'Curso de Especialização em Violência Doméstica'],
  'Artigos sobre implementação da Lei Maria da Penha no Estado do Rio de Janeiro',
  true,
  true,
  'user'
),
(
  'Dr. Carlos Eduardo Mendes',
  'MAT002',
  'carlos.mendes@mprj.mp.br',
  ARRAY['Procurador de Justiça'],
  ARRAY['Assessor Técnico'],
  ARRAY['Procuradoria-Geral de Justiça'],
  '(21) 2334-5679',
  'Procurador de Justiça com vasta experiência em direito administrativo e controle externo da administração pública.',
  ARRAY['Direito Administrativo', 'Controle Externo', 'Licitações e Contratos'],
  'Mestrado em Direito Administrativo',
  ARRAY['Transparência Pública', 'Combate à Corrupção', 'Gestão Pública'],
  ARRAY['Português', 'Inglês', 'Francês'],
  '/lovable-uploads/eb6ec157-e1f5-4ab6-9af7-6d9721b928ce.png',
  ARRAY['Certificação em Auditoria Governamental', 'Curso de Controle Externo'],
  'Livro: "Controle Externo da Administração Pública no Estado Democrático de Direito"',
  true,
  true,
  'user'
),
(
  'Ana Lucia Rodriguez',
  'MAT003',
  'ana.rodriguez@mprj.mp.br',
  ARRAY['Analista Ministerial'],
  ARRAY['Chefe de Seção'],
  ARRAY['Centro de Apoio Operacional'],
  '(21) 2334-5680',
  'Analista Ministerial especializada em meio ambiente e urbanismo, com foco em sustentabilidade e proteção ambiental.',
  ARRAY['Direito Ambiental', 'Urbanismo', 'Sustentabilidade'],
  'Especialização em Direito Ambiental e Urbanístico',
  ARRAY['Mudanças Climáticas', 'Proteção de Mananciais', 'Licenciamento Ambiental'],
  ARRAY['Português', 'Inglês', 'Espanhol'],
  '/lovable-uploads/73382607-1985-4ee0-b4b3-9dcdb6e612d1.png',
  ARRAY['ISO 14001', 'Certificação em Gestão Ambiental'],
  'Pesquisa sobre impactos ambientais na Baía de Guanabara',
  true,
  true,
  'user'
),
(
  'Prof. Hiroshi Tanaka',
  'MAT004',
  'hiroshi.tanaka@mprj.mp.br',
  ARRAY['Promotor de Justiça'],
  ARRAY['Supervisor'],
  ARRAY['Promotoria de Justiça'],
  '(21) 2334-5681',
  'Promotor especializado em crimes econômicos e lavagem de dinheiro, com doutorado em Direito Penal Econômico.',
  ARRAY['Direito Penal Econômico', 'Lavagem de Dinheiro', 'Crimes Financeiros'],
  'Doutorado em Direito Penal Econômico',
  ARRAY['Compliance', 'Crimes Cibernéticos', 'Cooperação Internacional'],
  ARRAY['Português', 'Japonês', 'Inglês'],
  '/lovable-uploads/8fa59876-e1fd-4ff1-840b-46e7e754da2c.png',
  ARRAY['Certificação Anti-Lavagem de Dinheiro', 'Curso de Crimes Financeiros'],
  'Tese: "Aspectos Penais da Lavagem de Dinheiro no Sistema Financeiro Brasileiro"',
  true,
  true,
  'user'
),
(
  'Lucas Gabriel Oliveira',
  'MAT005',
  'lucas.oliveira@mprj.mp.br',
  ARRAY['Técnico Ministerial'],
  ARRAY['Assessor'],
  ARRAY['Subprocuradoria-Geral de Justiça de Assuntos Administrativos'],
  '(21) 2334-5682',
  'Técnico Ministerial especializado em tecnologia da informação e transformação digital do Ministério Público.',
  ARRAY['Tecnologia da Informação', 'Transformação Digital', 'Segurança da Informação'],
  'Especialização em Segurança da Informação',
  ARRAY['Inovação Tecnológica', 'Sistemas de Gestão', 'Proteção de Dados'],
  ARRAY['Português', 'Inglês'],
  '/lovable-uploads/aa5b95cf-6b5f-4c6a-ac24-117cc0f073f1.png',
  ARRAY['CISSP', 'ITIL Foundation', 'Scrum Master'],
  'Artigos sobre implementação de sistemas digitais no MP',
  true,
  true,
  'user'
),
(
  'Dra. Fernanda Costa Lima',
  'MAT006',
  'fernanda.lima@mprj.mp.br',
  ARRAY['Promotora de Justiça'],
  ARRAY['Coordenadora'],
  ARRAY['Promotoria de Justiça'],
  '(21) 2334-5683',
  'Promotora especializada em direitos da criança e adolescente, com atuação em proteção integral e medidas socioeducativas.',
  ARRAY['Direito da Criança e Adolescente', 'Medidas Socioeducativas', 'Proteção Integral'],
  'Mestrado em Direitos da Criança e Adolescente',
  ARRAY['Estatuto da Criança e Adolescente', 'Adoção', 'Violência Infantil'],
  ARRAY['Português', 'Inglês'],
  '/lovable-uploads/64e7a9b5-7c7d-4a9c-8f97-18929c02ccc8.png',
  ARRAY['Certificação em Proteção Integral', 'Curso de Medidas Socioeducativas'],
  'Manual de Boas Práticas em Proteção à Criança e Adolescente',
  true,
  true,
  'user'
),
(
  'Dr. André Martins Santos',
  'MAT007',
  'andre.santos@mprj.mp.br',
  ARRAY['Analista Ministerial'],
  ARRAY['Assessor Técnico'],
  ARRAY['Corregedoria-Geral do Ministério Público'],
  '(21) 2334-5684',
  'Analista especializado em auditoria e correição, com foco em controle interno e compliance institucional.',
  ARRAY['Auditoria', 'Correição', 'Compliance'],
  'Especialização em Auditoria e Controle Interno',
  ARRAY['Controle Interno', 'Governança', 'Gestão de Riscos'],
  ARRAY['Português', 'Inglês'],
  '/lovable-uploads/26594df3-55f3-4aae-9c4a-5bbc9a54b487.png',
  ARRAY['Certificação em Auditoria Interna', 'Curso de Compliance'],
  'Estudos sobre controle interno no Ministério Público',
  true,
  true,
  'user'
),
(
  'Dr. Roberto Silva Mendoza',
  'MAT008',
  'roberto.mendoza@mprj.mp.br',
  ARRAY['Procurador de Justiça'],
  ARRAY['Coordenador'],
  ARRAY['Procuradoria-Geral de Justiça'],
  '(21) 2334-5685',
  'Procurador com expertise em direito eleitoral e democracia, atuando na defesa da ordem jurídica democrática.',
  ARRAY['Direito Eleitoral', 'Democracia', 'Direitos Políticos'],
  'Doutorado em Direito Constitucional',
  ARRAY['Processo Eleitoral', 'Financiamento de Campanhas', 'Combate à Corrupção Eleitoral'],
  ARRAY['Português', 'Espanhol', 'Inglês'],
  '/lovable-uploads/d7b2bd62-c617-4683-b3a1-4774712d0c86.png',
  ARRAY['Certificação em Direito Eleitoral', 'Curso de Democracia e Eleições'],
  'Livro: "Democracia e Ministério Público: Desafios Contemporâneos"',
  true,
  true,
  'user'
),
(
  'Dra. Aisha Al-Rahman Silva',
  'MAT009',
  'aisha.silva@mprj.mp.br',
  ARRAY['Promotora de Justiça'],
  ARRAY['Assessora'],
  ARRAY['Centro de Apoio Operacional'],
  '(21) 2334-5686',
  'Promotora especializada em direitos humanos e diversidade, com foco em proteção de minorias e combate à discriminação.',
  ARRAY['Direitos Humanos', 'Diversidade', 'Antidiscriminação'],
  'Mestrado em Direitos Humanos e Diversidade',
  ARRAY['Igualdade Racial', 'Liberdade Religiosa', 'Inclusão Social'],
  ARRAY['Português', 'Árabe', 'Inglês'],
  '/lovable-uploads/64bf9fe0-187a-425b-8204-edbaa7957745.png',
  ARRAY['Certificação em Direitos Humanos', 'Curso de Diversidade e Inclusão'],
  'Pesquisa sobre proteção de minorias religiosas no Brasil',
  true,
  true,
  'user'
),
(
  'Dr. Rajesh Patel Kumar',
  'MAT010',
  'rajesh.kumar@mprj.mp.br',
  ARRAY['Analista Ministerial'],
  ARRAY['Chefe de Seção'],
  ARRAY['Subprocuradoria-Geral de Justiça de Assuntos Administrativos'],
  '(21) 2334-5687',
  'Analista especializado em gestão financeira e orçamentária, com vasta experiência em planejamento e controle orçamentário.',
  ARRAY['Gestão Financeira', 'Orçamento Público', 'Planejamento Estratégico'],
  'Mestrado em Administração Pública',
  ARRAY['Controle Orçamentário', 'Gestão de Recursos', 'Transparência Fiscal'],
  ARRAY['Português', 'Hindi', 'Inglês'],
  '/lovable-uploads/ef815763-5b38-4f20-860b-7d5202b46536.png',
  ARRAY['Certificação em Gestão Pública', 'Curso de Orçamento Público'],
  'Manual de Gestão Orçamentária para o Ministério Público',
  true,
  true,
  'user'
);
