// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjnkcjoukokosaninytj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbmtjam91a29rb3NhbmlueXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM2NjUsImV4cCI6MjA2NTUxOTY2NX0.QCUz3EQemjHWlvLIX7_PlZUvid6HwcbKIuj1Gi9agfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);